// words used by the game engine
export default {
  animal: [
    "elephant",
    "penguin",
    "giraffe",
    "kangaroo",
    "dolphin",
    "hamster",
    "octopus",
    "cheetah",
    "platypus",
    "gorilla",
    "lion",
    "tiger",
    "zebra",
    "panda",
    "koala",
    "wolf",
    "fox",
    "rabbit",
    "squirrel",
    "hedgehog",
    "crocodile",
    "turtle",
    "frog",
    "eagle",
    "owl",
    "parrot",
    "shark",
    "whale",
    "horse",
    "monkey",
  ],
  celebrity: [
    "Beyonce",
    "Tom Hanks",
    "Taylor Swift",
    "Elon Musk",
    "Brad Pitt",
    "Rihanna",
    "Lionel Messi",
    "Oprah Winfrey",
    "Jackie Chan",
    "Lady Gaga",
    "Cristiano Ronaldo",
    "Will Smith",
    "Angelina Jolie",
    "Dwayne Johnson",
    "Adele",
    "Bill Gates",
    "Meryl Streep",
    "Leonardo DiCaprio",
    "Serena Williams",
    "Justin Bieber",
    "Jennifer Aniston",
    "Robert Downey Jr",
    "Kim Kardashian",
    "David Beckham",
    "Emma Watson",
    "Stephen Hawking",
    "Malala Yousafzai",
    "Barack Obama",
    "Shakira",
    "Tom Cruise",
  ],
  country: [
    "Switzerland",
    "Japan",
    "Brazil",
    "Australia",
    "Canada",
    "Egypt",
    "Norway",
    "Thailand",
    "Mexico",
    "Iceland",
    "France",
    "Italy",
    "India",
    "South Africa",
    "New Zealand",
    "Greece",
    "South Korea",
    "Argentina",
    "Kenya",
    "Vietnam",
  ],
  sports: [
    "basketball",
    "tennis",
    "cricket",
    "volleyball",
    "badminton",
    "football",
    "soccer",
    "rugby",
    "hockey",
    "boxing",
    "wrestling",
    "cycling",
    "skiing",
    "surfing",
    "karate",
    "baseball",
    "swimming",
    "fencing",
    "archery",
    "golf",
  ],
};
